services:
  postgres:
    image: postgres:13.22-trixie
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data   # 自動建立 volume

volumes:
  pg_data: